### ISSUE TITLE
Quicklisp issues

### ISSUE THREAD

**Issue by MrKolt** [lispbuilder/lispbuilder#52]
I'm having a lot of issues installing it since I don't use ASDF (I'm always recommended not to, and I don't even think I have it installed) Is there any support coming for quicklisp?

**Comment by elliottslaughter** [comment]
Yes, Quicklisp is supported. You will need to install SDL yourself, but after that you can just

    (ql:quickload :lispbuilder-sdl)

I should also mention that you *are* using ASDF, whether you realize it or not. (The very first thing that Quicklisp always does is to install ASDF, or upgrade it if the previously installed version is old.) Quicklisp is just responsible for downloading the (source code for) libraries; ASDF is still in charge of actually building everything. So, for example, it is still considered a best practice to provide an ASDF system definition file (`.asd`) for your own projects, so that all the dependencies are automatically loaded. You can even use such a file in combination with Quicklisp to automatically download all your dependencies from the internet.

Hope that helps. Feel free to reply to this issue if you have any other questions.

**Comment by elliottslaughter** [comment]
Also, if you want more information on defining your own projects with ASDF, you can [read up on it in the ASDF manual](https://common-lisp.net/project/asdf/asdf.html#Defining-systems-with-defsystem).

If you're using Quicklisp, you can ignore all the instructions on installing and using ASDF itself. Once you've set up your `.asd` file, just call Quicklisp as usual, e.g.:

    (ql:quickload :hello-lisp)

(This is assuming you copy-and-pasted the very first example in the manual.)

**Comment by MrKolt** [comment]
Thank you, that's really helpful.
