### ISSUE TITLE
SDL returning null pointer

### ISSUE THREAD

**Issue by RealSharpness** [lispbuilder/lispbuilder#74]
Apologies if this is the wrong place to post.

Whenever I start up my game for testing it works fine; from the second time onwards after a few seconds I get the error "attempt to call T which is an undefined function". Point of error is function load-image from image.lisp according to the debugger. I suspect it has something to do with memory management but struggling to find a lead.

 ```
 (ERROR #<UNDEFINED-FUNCTION @ #x226ee6ba>)
 ->(T NIL)
   (T NIL)
   ((:INTERNAL (:INTERNAL (METHOD INITIALIZE-INSTANCE :AROUND (SDL::FOREIGN-OBJECT)) 0) 0))
   ((:INTERNAL TG:FINALIZE 0) #<ZONE @ #x226d00f2>)
   ((METHOD MAKE-INSTANCE (CLASS)) #<STANDARD-CLASS EXCL:PROBE-SIMPLE-STREAM> :INPUT-HANDLE ...)
   ((METHOD MAKE-INSTANCE (SYMBOL)) EXCL:PROBE-SIMPLE-STREAM :INPUT-HANDLE ...)
   (OPEN #P"C:\\Users\\hugo1" :DIRECTION ...)
   (PROBE-FILE "C:\\Users\\user1")
```
Any advice would be much appreciated.

**Comment by elliottslaughter** [comment]
Just to clarify, "second time on" means you're re-initializing Lispbuilder-SDL within the same process?

It's been a while but I don't remember if that works properly (or there may be a certain way you need to do it so that it works), but maybe one of the other old-timers can chime in here. @Balooga

**Comment by RealSharpness** [comment]
That's right, it's initialised via WITH-INIT and I close the window manually to exit.
I can do a quick recompile as a workaround, otherwise I'd have to restart lisp.

Just curious if any ideas come to mind.
So grateful for lispbuilder, it's my passion!

**Comment by Balooga** [comment]
I think your problem is as @elliottslaughter described.

Can you try setting `*quit-on-exit*` to `nil` following `with-init` ? I think `(sdl::set-quit-on-exit nil)` will do it. Or `(setf sdl:quit-on-exit nil)`. This will cause `with-init` to not tear down the SDL subsystems between invocations.

https://github.com/lispbuilder/lispbuilder/blob/589b3c6d552bbec4b520f61388117d6c7b3de5ab/lispbuilder-sdl/sdl/init.lisp#L86

If this doesn't work, there is a way to specify the SDL sub-systems you want to initialize on startup and exit.

**Comment by RealSharpness** [comment]
Resolved, I was unnecessarily subclassing SDL-SURFACE with my game objects. Issue no longer persists after fixing this. Thanks again for your time.
